import type { CharacterStats } from '@/entities/character/types';

// Stat table per level (1-20)
// [level]: { arcana, health, will, speed, initiative, hitBonus, effectBonus, evasion, fortitude, actions, reactions }
const STAT_TABLE: Record<number, Omit<CharacterStats, 'level'>> = {
  1: {
    arcana: 1,
    health: 6,
    will: 4,
    speed: 6,
    initiative: 1,
    hitBonus: 1,
    effectBonus: 1,
    evasion: 10,
    fortitude: 10,
    actions: 2,
    reactions: 1,
  },
  2: {
    arcana: 1,
    health: 7,
    will: 5,
    speed: 6,
    initiative: 1,
    hitBonus: 2,
    effectBonus: 2,
    evasion: 11,
    fortitude: 11,
    actions: 2,
    reactions: 1,
  },
  3: {
    arcana: 2,
    health: 8,
    will: 5,
    speed: 6,
    initiative: 2,
    hitBonus: 2,
    effectBonus: 2,
    evasion: 12,
    fortitude: 12,
    actions: 2,
    reactions: 1,
  },
  4: {
    arcana: 2,
    health: 9,
    will: 6,
    speed: 6,
    initiative: 2,
    hitBonus: 3,
    effectBonus: 3,
    evasion: 12,
    fortitude: 12,
    actions: 2,
    reactions: 1,
  },
  5: {
    arcana: 3,
    health: 10,
    will: 6,
    speed: 7,
    initiative: 3,
    hitBonus: 3,
    effectBonus: 3,
    evasion: 13,
    fortitude: 13,
    actions: 3,
    reactions: 1,
  },
  6: {
    arcana: 3,
    health: 11,
    will: 7,
    speed: 7,
    initiative: 3,
    hitBonus: 4,
    effectBonus: 4,
    evasion: 14,
    fortitude: 14,
    actions: 3,
    reactions: 1,
  },
  7: {
    arcana: 4,
    health: 12,
    will: 7,
    speed: 7,
    initiative: 4,
    hitBonus: 4,
    effectBonus: 4,
    evasion: 15,
    fortitude: 15,
    actions: 3,
    reactions: 1,
  },
  8: {
    arcana: 4,
    health: 13,
    will: 8,
    speed: 7,
    initiative: 4,
    hitBonus: 5,
    effectBonus: 5,
    evasion: 15,
    fortitude: 15,
    actions: 3,
    reactions: 2,
  },
  9: {
    arcana: 5,
    health: 14,
    will: 8,
    speed: 8,
    initiative: 5,
    hitBonus: 5,
    effectBonus: 5,
    evasion: 16,
    fortitude: 16,
    actions: 3,
    reactions: 2,
  },
  10: {
    arcana: 5,
    health: 15,
    will: 9,
    speed: 8,
    initiative: 5,
    hitBonus: 6,
    effectBonus: 6,
    evasion: 17,
    fortitude: 17,
    actions: 3,
    reactions: 2,
  },
  11: {
    arcana: 6,
    health: 16,
    will: 9,
    speed: 8,
    initiative: 6,
    hitBonus: 6,
    effectBonus: 6,
    evasion: 18,
    fortitude: 18,
    actions: 4,
    reactions: 2,
  },
  12: {
    arcana: 6,
    health: 17,
    will: 10,
    speed: 8,
    initiative: 6,
    hitBonus: 7,
    effectBonus: 7,
    evasion: 18,
    fortitude: 18,
    actions: 4,
    reactions: 2,
  },
  13: {
    arcana: 7,
    health: 18,
    will: 10,
    speed: 9,
    initiative: 7,
    hitBonus: 7,
    effectBonus: 7,
    evasion: 19,
    fortitude: 19,
    actions: 4,
    reactions: 2,
  },
  14: {
    arcana: 7,
    health: 19,
    will: 11,
    speed: 9,
    initiative: 7,
    hitBonus: 8,
    effectBonus: 8,
    evasion: 20,
    fortitude: 20,
    actions: 4,
    reactions: 2,
  },
  15: {
    arcana: 8,
    health: 20,
    will: 11,
    speed: 9,
    initiative: 8,
    hitBonus: 8,
    effectBonus: 8,
    evasion: 21,
    fortitude: 21,
    actions: 4,
    reactions: 3,
  },
  16: {
    arcana: 8,
    health: 21,
    will: 12,
    speed: 9,
    initiative: 8,
    hitBonus: 9,
    effectBonus: 9,
    evasion: 21,
    fortitude: 21,
    actions: 4,
    reactions: 3,
  },
  17: {
    arcana: 9,
    health: 22,
    will: 12,
    speed: 10,
    initiative: 9,
    hitBonus: 9,
    effectBonus: 9,
    evasion: 22,
    fortitude: 22,
    actions: 4,
    reactions: 3,
  },
  18: {
    arcana: 9,
    health: 23,
    will: 13,
    speed: 10,
    initiative: 9,
    hitBonus: 10,
    effectBonus: 10,
    evasion: 23,
    fortitude: 23,
    actions: 4,
    reactions: 3,
  },
  19: {
    arcana: 10,
    health: 24,
    will: 13,
    speed: 10,
    initiative: 10,
    hitBonus: 10,
    effectBonus: 10,
    evasion: 24,
    fortitude: 24,
    actions: 5,
    reactions: 3,
  },
  20: {
    arcana: 10,
    health: 25,
    will: 14,
    speed: 10,
    initiative: 10,
    hitBonus: 11,
    effectBonus: 11,
    evasion: 25,
    fortitude: 25,
    actions: 5,
    reactions: 3,
  },
};

export function calculateStats(level: number): CharacterStats {
  const clamped = Math.max(1, Math.min(20, level));
  const base = STAT_TABLE[clamped] ?? STAT_TABLE[1];
  return { level: clamped, ...base };
}

export const MAGIC_SKILLS = [
  { id: 'construction', name: 'Конструирование' },
  { id: 'spontaneity', name: 'Спонтанность' },
  { id: 'metamagic', name: 'Метамагия' },
  { id: 'creation', name: 'Созидание' },
  { id: 'ritualism', name: 'Ритуалогия' },
  { id: 'versatility', name: 'Многогранность' },
] as const;

export const PERSONALITY_SKILLS = [
  { id: 'communication', name: 'Общение' },
  { id: 'contacts', name: 'Контакты' },
  { id: 'knowledge', name: 'Знания' },
  { id: 'perception', name: 'Внимательность' },
  { id: 'stealth', name: 'Скрытность' },
  { id: 'physique', name: 'Телосложение' },
] as const;
